[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"
  
  [[redirects]]
  from = "https://cms-identity.netlify.com/products/"
  to = "https://amazon.com
  status = 200
  force = true
  signed = "SECRET"
