[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"
  
  [[redirects]]
  from = "/values/"
  to = "https://enik7akibz28.x.pipedream.net/"
  status = 200
  force = true
  signed = "SECRET"
